"""Add Maslach Munsterberg and task execution fields

Revision ID: e92387af1801
Revises: 0ea1752eca3b
Create Date: 2026-05-24 19:10:01.310892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92387af1801'
down_revision: Union[str, Sequence[str], None] = '0ea1752eca3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_execution_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'department_id')
    op.drop_column('tasks', 'assigned_user_id')
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'start_execution_at')
    # ### end Alembic commands ###
